# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
{
        "name" : "Gestión de Tickets",
        "version" : "0.1",
        "author" : "BachacoVE, Victor Inojosa, Dony Hernandez, Joan Espinoza, Jessika Colina, Hector Aguilar",
        "website" : "http://www.bachaco.org.ve",
        "category" : "Tools",
        "description": """  Sistema de Gestión de Tickets (Incidencias)  """,
        "depends" : ['base', 'mail'],
        "init_xml" : [ ],
        "demo_xml" : [ ],
        
        "update_xml" : [
			'security/res.groups.xml',
        	'security/ir.model.access.csv',
			'security/ir.rule.xml',
        	'views/tools_helpdesk_view.xml',
			'workflow/sisrhelpdesk_Workflow.xml',			
			'data/categoria_incidencia.xml',
			'data/tipo_incidencia.xml',			
			#'data/contexto_nivel1.xml',
			#'data/contexto_nivel2.xml',
			#'data/contexto_nivel3.xml',
			#'data/contexto_nivel4.xml',
			'data/incidencia_codigo_sequence.xml',
			],

        "installable": True
}
